import { Pokemon } from "./IPokemon";

export const pokemons: Pokemon[] = [
  {
    nom: "Dracaufeu",
    type: "Feu",
    pv: 78,
    pvMax: 78,
    attaque: 84,
    defense: 78,
    vitesse: 100,
    attaques: [
      { nom: "Lance-Flammes", puissance: 90, type: "Feu" },
      { nom: "Crocs Feu", puissance: 65, type: "Feu" },
    ],
  },
  {
    nom: "Tortank",
    type: "Eau",
    pv: 79,
    pvMax: 79,
    attaque: 83,
    defense: 100,
    vitesse: 78,
    attaques: [
      { nom: "Hydrocanon", puissance: 110, type: "Eau" },
      { nom: "Bulles d'O", puissance: 40, type: "Eau" },
    ],
  },
  {
    nom: "Florizarre",
    type: "Plante",
    pv: 80,
    pvMax: 80,
    attaque: 82,
    defense: 83,
    vitesse: 80,
    attaques: [
      { nom: "Lance-Soleil", puissance: 120, type: "Plante" },
      { nom: "Syntoniseur", puissance: 0, type: "Plante", soin: true },
    ],
  },
  {
    nom: "Pikachu",
    type: "Électrik",
    pv: 35,
    pvMax: 35,
    attaque: 55,
    defense: 40,
    vitesse: 90,
    attaques: [{ nom: "Éclair", puissance: 90, type: "Électrik" }],
  },
  {
    nom: "Grolem",
    type: "Roche",
    pv: 80,
    pvMax: 80,
    attaque: 110,
    defense: 130,
    vitesse: 45,
    attaques: [{ nom: "Jet-Pierres", puissance: 50, type: "Roche" }],
  },
  {
    nom: "Onix",
    type: "Sol",
    pv: 35,
    pvMax: 35,
    attaque: 45,
    defense: 160,
    vitesse: 70,
    attaques: [{ nom: "Séisme", puissance: 100, type: "Sol" }],
  },
  {
    nom: "Roucarnage",
    type: "Vol",
    pv: 83,
    pvMax: 83,
    attaque: 80,
    defense: 75,
    vitesse: 101,
    attaques: [{ nom: "Cru-Aile", puissance: 60, type: "Vol" }],
  },
  {
    nom: "Alakazam",
    type: "Psy",
    pv: 55,
    pvMax: 55,
    attaque: 50,
    defense: 45,
    vitesse: 120,
    attaques: [{ nom: "Choc Mental", puissance: 90, type: "Psy" }],
  },
  {
    nom: "Lokhlass",
    type: "Glace",
    pv: 130,
    pvMax: 130,
    attaque: 85,
    defense: 80,
    vitesse: 60,
    attaques: [{ nom: "Laser Glace", puissance: 90, type: "Glace" }],
  },
  {
    nom: "Dracolosse",
    type: "Dragon",
    pv: 91,
    pvMax: 91,
    attaque: 134,
    defense: 95,
    vitesse: 80,
    attaques: [{ nom: "Draco-Griffe", puissance: 80, type: "Dragon" }],
  },
];
